name: gluon
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - scikit-optimize
  - xgboost
  - joblib
  - matplotlib
  - seaborn
  - altair
  - statsmodels
  - jupyter
  - ipykernel
